version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: henriquedezani/elo7-server
    container_name: server
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/api"
      - "../data:/usr/src/data"
    env_file: ".env"